default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Reverse Proxy Configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.30.15    # The IP of your Nginx Proxy Manager

lovelace:
  mode: yaml
input_select:
  presence_jackie:
    name: Jackie
    options:
      - Home
      - Not Home
      - "Timeout (Home)"
      - "Timeout (Not Home)"
    initial: "Not Home"
    icon: mdi:account

  presence_chris:
    name: Chris
    options:
      - Home
      - Not Home
      - "Timeout (Home)"
      - "Timeout (Not Home)"
    initial: "Not Home"
    icon: mdi:account

  presence_callie:
    name: Callie
    options:
      - Home
      - Not Home
      - "Timeout (Home)"
      - "Timeout (Not Home)"
    initial: "Not Home"
    icon: mdi:account
