title: Home

resources:
  - url: /hacsfiles/lovelace-mushroom/mushroom.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module

views:
  - title: Overview
    path: overview
    icon: mdi:home
    cards:

      # WHO'S HOME
      - type: entities
        title: Who's Home
        entities:
          - entity: person.edward_ciarletta
            name: Eddie
          - entity: input_select.presence_jackie
            name: Jackie
            icon: mdi:account
          - entity: input_select.presence_chris
            name: Chris
            icon: mdi:account
          - entity: input_select.presence_callie
            name: Callie
            icon: mdi:account

      # CAMERAS
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: Front Door
            camera_image: camera.front_door_fluent
            entities:
              - entity: lock.front_door_lock
              - entity: binary_sensor.front_door_person
              - entity: binary_sensor.front_door_motion
          - type: picture-glance
            title: Back Door
            camera_image: camera.back_door_fluent
            entities:
              - entity: lock.downstairs_kitchen_door_lock
              - entity: binary_sensor.back_door_person
              - entity: binary_sensor.back_door_motion

      # LOCKS
      - type: glance
        title: Locks
        columns: 2
        entities:
          - entity: lock.front_door_lock
            name: Front Door
          - entity: lock.downstairs_kitchen_door_lock
            name: Kitchen Door
          - entity: lock.gym_door_lock
            name: Gym Door
          - entity: lock.shed_door_lock
            name: Shed Door
